### ISSUE TITLE
Add Cocoapods support

### ISSUE THREAD

**Issue by mugbug** [mugbug/BricksAndTiles#14]
Create a .podspec file for this project (so it's ready to be published)

Would be interesting for it to be separated by subspecs (TableView/CollectionView folders), but I'm not sure if that's currently possible

obs: it depends uppon `pod 'PaintAndBrush', '0.1.4'`

**Comment by aryasurya21** [comment]
hello, could you please elaborate more on this issue? i would like to help @mugbug

**Comment by mugbug** [comment]
Do you think that's enough? @aryasurya21

**Comment by Recouse** [comment]
Hi,
Created pull requests with podspec files. Also, added subspecs for CollectionView and TableView.
