### ISSUE TITLE
Add preview gif/image for all features

### ISSUE THREAD

**Issue by mugbug** [mugbug/BricksAndTiles#15]

**Comment by jamie-brannan** [comment]
Hello @mugbug 👋  I'm participating in Hacktoberfest this year and would like to take on this issue if it's still available!

**Comment by mugbug** [comment]
Hi @jamie-brannan! Just go for it! =]

**Comment by jamie-brannan** [comment]
Hello again, I don't seem to have access rights to push my branch yet. 🚧 👷‍♀️

**Comment by jamie-brannan** [comment]
Nevermind, just learned about making pull requests via forks 😅 Still new!

**Comment by mugbug** [comment]
Hey @jamie-brannan, if you need some help creating PRs just let me know =]

**Comment by jamie-brannan** [comment]
Hello! No worries I've got this – I expected busy the past few days but this is my priority tonight! Thank you for your patience.

**Comment by mugbug** [comment]
Hey @jamie-brannan, no problem! Take your time =]
