### ISSUE TITLE
Create an awesome logo for this repo =]

### ISSUE THREAD

**Issue by mugbug** [mugbug/BricksAndTiles#31]
Suggestions:
- Would be a good idea to have the repo name on it
- Add it to README.md already
- The awesome level expected would be something near WOW awesome 😎
- It'll be a good idea also for it to have a transparent background

**Comment by kavita121** [comment]
Can I work on this??

**Comment by mugbug** [comment]
There's a PR open already #32, but I'm not sure if it's going forward. So go for it =]

**Comment by kavita121** [comment]
okay thanks :)

**Comment by kavita121** [comment]
Heyy!! I have made a design

**Comment by kavita121** [comment]
Heyy I guess I was supposed to make the logo for Bricks and Tiles. I made one for mugbugs please agree to see and if possible please help me with hacktoberfest

**Comment by mugbug** [comment]
Hello!

**Comment by kavita121** [comment]
Okay thanks I'll do it by evening. :)

**Comment by kavita121** [comment]
please check I've created a pull request :)

**Comment by Roshanpaswan** [comment]
I have made new logo please check it out.

**Comment by mugbug** [comment]
Hello @kavita121 and @Roshanpaswan! Thank you so much for your contributions! 
I just think we could have a more minimalistic logo (but we can still play with the bricks/tiles idea), those weren't exactly what I was expecting. To give some examples, I thought of something like the ones from these repos:
- https://github.com/JohnSundell/Splash
- https://github.com/Alamofire/Alamofire
- https://github.com/zenangst/Blueprints

What do you think?

**Comment by Roshanpaswan** [comment]
Added new Logo Design please check it out!

**Comment by kavita121** [comment]
Okayy!! I will try to make a new one :)
